/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diego
 */
public class FrameSueldos extends javax.swing.JFrame {

    /**
     * Creates new form FrameSueldos
     */
    public FrameSueldos() {
        initComponents();
        this.setTitle("Sistema de Planillas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBO = new javax.swing.ButtonGroup();
        Panel1 = new javax.swing.JPanel();
        L1 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        L2 = new javax.swing.JLabel();
        TxtHEx = new javax.swing.JTextField();
        CmdAceptar = new javax.swing.JButton();
        Panel2 = new javax.swing.JPanel();
        RG = new javax.swing.JRadioButton();
        RP = new javax.swing.JRadioButton();
        CmdOperacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        L1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        L1.setText("Nombre:");

        TxtNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        L2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        L2.setText("Horas Extra:");

        TxtHEx.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        CmdAceptar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CmdAceptar.setText("Aceptar");
        CmdAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L2)
                    .addComponent(L1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtHEx, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addComponent(CmdAceptar)
                        .addGap(73, 73, 73)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L2)
                    .addComponent(TxtHEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CmdAceptar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        GrupoBO.add(RG);
        RG.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RG.setText("Aumento Salarial Generalizado");

        GrupoBO.add(RP);
        RP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RP.setText("Aumento Salarial por Empleado");

        CmdOperacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CmdOperacion.setText("Ejecutar");
        CmdOperacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmdOperacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RG)
                    .addComponent(RP))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CmdOperacion)
                .addGap(61, 61, 61))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CmdOperacion)
                .addContainerGap())
        );

        TbData.setBackground(new java.awt.Color(102, 102, 102));
        TbData.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        TbData.setForeground(new java.awt.Color(255, 255, 255));
        TbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Sueldo Ordinario", "Sueldo Extra", "Bonificación", "Otros", "Total Ingreso", "IGSS", "ISR", "Otros", "Total Descuentosl", "Sueldo Líquido"
            }
        ));
        jScrollPane1.setViewportView(TbData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 262, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /*------© DIEGO VÁSQUEZ 9959-19-19543 -PROGRA I---//
                LABORATORIO #2
    ---------------------------------------------------*/
    //--- SALARIO MÍNIMO ES UNA CONSTANTE ---//
    static final double DSalMin=2825.15;
    //--- BONIFICACIÓN LEGAL ES UNA CONSTANTE ---//
    static final double DBonusLeg = 250;
    //--- VARIABLE CÓDIGO ---//
    int ICod=0;
    private void CmdAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdAceptarActionPerformed
        try{
            int IHorasEx; double DPgoHEx;
            //-----------------------------//
            String SNomEmp;
            //-----------------------------//
            SNomEmp=TxtNombre.getText();
            IHorasEx=Integer.parseInt(TxtHEx.getText());
            //-----------------------------------------//
            DPgoHEx=1.5*IHorasEx;
            //--------------------//
            //--- RANDOM DE 1 A 3500 ---//
            int IOtrosIng = (int)(Math.random()*3500+1);
            //--- RANDOM DE 1 A 1000 ---//
            int IOtrosG = (int)(Math.random()*1000+1);
            //------------------------------------------------//
            double DSalBruto;
            DSalBruto = DSalMin+DPgoHEx+DBonusLeg+IOtrosIng;
            //-------------------------------------------------//
            double DISR=0;
            if(DSalBruto>6000&&DSalBruto<8000){
                DISR=DSalBruto*0.05;
            }
            else if(DSalBruto>8000&&DSalBruto<9500){
                DISR=DSalBruto*0.06;
            }
            else if(DSalBruto>9500){
                DISR=DSalBruto*0.08;
            }
            double DIGSS;
            DIGSS=DSalBruto*0.0483;
            //---------------------------//
            double DTotDesc;
            DTotDesc = DISR+DIGSS+IOtrosG;
            //---------------------------//
            double DSalLiq=0;
            DSalLiq=DSalBruto-DTotDesc;
            //------------------------------------//
            Object[] VData = new Object[12];
            DefaultTableModel modelo = (DefaultTableModel) TbData.getModel();
            ICod++;
            VData[0]=String.valueOf(ICod);
            VData[1]=SNomEmp;
            VData[2]=String.valueOf(DSalMin);
            VData[3]=String.valueOf(DPgoHEx);
            VData[4]=String.valueOf(DBonusLeg);
            VData[5]=String.valueOf(IOtrosIng);
            VData[6]=String.valueOf(DSalBruto);
            VData[7]=String.valueOf(DIGSS);
            VData[8]=String.valueOf(DISR);
            VData[9]=String.valueOf(IOtrosG);
            VData[10]=String.valueOf(DTotDesc);
            VData[11]=String.valueOf(DSalLiq);
            modelo.addRow(VData);
            TbData.setModel(modelo);
            //-------------------------------//
            TxtNombre.setText("");
            TxtHEx.setText("");
            TxtNombre.requestFocus();
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "VERIFIQUE LA INFORMACIÓN");
        }     
    }//GEN-LAST:event_CmdAceptarActionPerformed

    private void CmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmdOperacionActionPerformed
       /*------© DIEGO VÁSQUEZ 9959-19-19543 -PROGRA I---//
                LABORATORIO #2
         ---------------------------------------------------*/
        int n;
        n=TbData.getRowCount();
        String[][] MatInf = new String[n][12];
        //------------------------------------//
        double DAuSal=0;
        double DPorcentaje=0;
        //-----------------------//
        double DPgEx=0;
        double DIng=0;
        double DTotIng=0;
        double DIGSS=0;
        double DISR=0;
        double DOtrosD=0;
        double DTotD=0;
        double DSLiq=0;
        //-----------------------//
        DPorcentaje = Double.parseDouble(JOptionPane.showInputDialog(null, "INGRESE % DE AUMENTO"));
        //--------TOMA DE INFORMACIÓN Y TRASLADO A MATRIZ---------//
        if(RG.isSelected()==true){
            for(int i=0; i<n; i++){
                for(int j=0; j<12; j++){
                    MatInf[i][j]= String.valueOf(TbData.getValueAt(i, j));
                }
            }
            //---- RECALCULO DE VALORES ----///
            DAuSal=DSalMin+(DSalMin*(DPorcentaje/100));
            for(int i=0; i<n; i++){
                DPgEx=Double.parseDouble(MatInf[i][3]);
                DIng=Double.parseDouble(MatInf[i][5]);
                DTotIng=DAuSal+DPgEx+DBonusLeg+DIng;
                
                if(DTotIng>6000&&DTotIng<8000){
                    DISR=DTotIng*0.05;
                }
                else if(DTotIng>8000&&DTotIng<9500){
                    DISR=DTotIng*0.06;
                }
                else if(DTotIng>9500){
                    DISR=DTotIng*0.08;
                }
                DIGSS=DTotIng*0.0483;
                DOtrosD=Double.parseDouble(MatInf[i][9]);
                DTotD=DIGSS+DISR+DOtrosD;
                DSLiq=DTotIng-DTotD;
                MatInf[i][2]=String.valueOf(DAuSal);
                MatInf[i][6]=String.valueOf(DTotIng);
                MatInf[i][10]=String.valueOf(DTotD);
                MatInf[i][11]=String.valueOf(DSLiq);
            }
            //-----MOSTRAR LOS DATOS MODIFICADOS-----//
             for(int i=0; i<n; i++){
                for(int j=0; j<12; j++){
                    TbData.setValueAt(String.valueOf(MatInf[i][j]), i, j);
                }
            }
        }
        else if(RP.isSelected()==true){
            //PENDIENTE
        }
    }//GEN-LAST:event_CmdOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSueldos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmdAceptar;
    private javax.swing.JButton CmdOperacion;
    private javax.swing.ButtonGroup GrupoBO;
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JPanel Panel1;
    private javax.swing.JPanel Panel2;
    private javax.swing.JRadioButton RG;
    private javax.swing.JRadioButton RP;
    private javax.swing.JTable TbData;
    private javax.swing.JTextField TxtHEx;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
